extends SceneTree

const ASSET_DIRS := ["assets", "scenes", "shaders", "translations", "data"]
const OUTPUT_PATH := "res://scripts/asset_registry.gd"

const EXCLUDE_DIRS := [".godot", ".git", ".github", ".opencode", "addons", "godot-mcp"]
const EXCLUDE_EXTENSIONS := ["import", "uid", "godot", "cfg", "md", "zip", "keystore"]

var entries := {}


func _init() -> void:
	for dir_name in ASSET_DIRS:
		var full_path := ProjectSettings.globalize_path(dir_name)
		if not DirAccess.dir_exists_absolute(full_path):
			continue
		_scan_dir(full_path, dir_name, entries)
	var code := _generate_code(entries)
	_write_file(code)
	print("AssetRegistry generated: %s  (%d constants)" % [OUTPUT_PATH, _count_constants(entries)])
	quit()


func _scan_dir(abs_path: String, rel_path: String, e: Dictionary) -> void:
	var dir := DirAccess.open(abs_path)
	if dir == null:
		return
	dir.list_dir_begin()
	var file_name := dir.get_next()
	while file_name != "":
		if file_name.begins_with("."):
			file_name = dir.get_next()
			continue
		var child_abs := abs_path.path_join(file_name)
		var child_rel := rel_path.path_join(file_name)
		if dir.current_is_dir():
			if file_name not in EXCLUDE_DIRS:
				_scan_dir(child_abs, child_rel, e)
		else:
			var ext := file_name.get_extension().to_lower()
			if ext in EXCLUDE_EXTENSIONS:
				file_name = dir.get_next()
				continue
			var folder := _get_folder(child_rel)
			if not e.has(folder):
				e[folder] = {}
			e[folder][_make_const_name(file_name, folder)] = "res://%s" % child_rel
		file_name = dir.get_next()
	dir.list_dir_end()


func _get_folder(rel_path: String) -> String:
	var parts := rel_path.split("/")
	# assets/icons/icon_chop.png → ["assets", "icons", "icon_chop.png"]  → "ICONS"
	# assets/player.png → ["assets", "player.png"]  → "ROOT"
	# scenes/click_effect.tscn → ["scenes", "click_effect.tscn"]  → "SCENES"
	if parts[0] == "assets":
		if parts.size() > 2:
			return parts[1].to_upper()
		return "ROOT"
	return parts[0].to_upper()


func _make_const_name(file_name: String, folder: String) -> String:
	var n := file_name.get_basename()
	n = n.replace("-", "_").replace(" ", "_").replace(".", "_")
	n = n.to_upper()
	if folder != "ROOT":
		n = folder + "_" + n
	return n


func _generate_code(e: Dictionary) -> String:
	var lines := PackedStringArray()
	lines.append("## AUTO-GENERATED by generate_asset_registry.gd — do not edit manually.")
	lines.append("class_name AssetRegistry")
	lines.append("")
	lines.append("")
	for folder in e:
		var consts: Dictionary = e[folder]
		lines.append("## %s" % folder)
		for key in consts:
			lines.append('const %s := "%s"' % [key, consts[key]])
		lines.append("")
	return "\n".join(lines)


func _count_constants(e: Dictionary) -> int:
	var total := 0
	for folder in e:
		total += e[folder].size()
	return total


func _write_file(code: String) -> void:
	var global_path := ProjectSettings.globalize_path(OUTPUT_PATH)
	var dir := DirAccess.open(ProjectSettings.globalize_path("res://scripts"))
	if dir and not dir.dir_exists_absolute("tools"):
		dir.make_dir_absolute("tools")
	var file := FileAccess.open(global_path, FileAccess.WRITE)
	if file == null:
		push_error("Cannot write to %s" % OUTPUT_PATH)
		return
	file.store_string(code)
	file.close()
