@tool
extends EditorScript

const ASSET_DIRS := ["assets", "scenes", "shaders", "translations", "data"]
const OUTPUT_PATH := "res://scripts/asset_registry.gd"

const EXCLUDE_DIRS := [".godot", ".git", ".github", ".opencode", "addons", "godot-mcp"]
const EXCLUDE_EXTENSIONS := [".import", ".godot", ".cfg", ".md", ".zip", ".keystore"]


func _run() -> void:
	var entries := {}
	for dir_name in ASSET_DIRS:
		var full_path := ProjectSettings.globalize_path(dir_name)
		if not DirAccess.dir_exists_absolute(full_path):
			continue
		_scan_dir(full_path, dir_name, entries, 0)
	var code := _generate_code(entries)
	_write_file(code)
	print("AssetRegistry generated: %s  (%d constants)" % [OUTPUT_PATH, _count_constants(entries)])


func _scan_dir(abs_path: String, rel_path: String, entries: Dictionary, depth: int) -> void:
	var dir := DirAccess.open(abs_path)
	if dir == null:
		return
	dir.list_dir_begin()
	var file_name := dir.get_next()
	while file_name != "":
		if file_name.begins_with("."):
			file_name = dir.get_next()
			continue
		var child_abs := abs_path.path_join(file_name)
		var child_rel := rel_path.path_join(file_name)
		if dir.current_is_dir():
			if file_name not in EXCLUDE_DIRS:
				_scan_dir(child_abs, child_rel, entries, depth + 1)
		else:
			var ext := file_name.get_extension().to_lower()
			if ext in EXCLUDE_EXTENSIONS:
				file_name = dir.get_next()
				continue
			var folder: String
			if depth <= 1:
				folder = "ROOT"
			else:
				folder = rel_path.get_file().to_upper()
			if not entries.has(folder):
				entries[folder] = {}
			entries[folder][_make_const_name(file_name, folder)] = "res://%s" % child_rel
		file_name = dir.get_next()
	dir.list_dir_end()


func _make_const_name(file_name: String, folder: String) -> String:
	var name := file_name.get_basename()
	name = name.replace("-", "_").replace(" ", "_").replace(".", "_")
	name = name.to_upper()
	if folder != "ROOT":
		name = folder + "_" + name
	return name


func _generate_code(entries: Dictionary) -> String:
	var lines := PackedStringArray()
	lines.append("## AUTO-GENERATED by generate_asset_registry.gd — do not edit manually.")
	lines.append("class_name AssetRegistry")
	lines.append("")
	lines.append("")
	for folder in entries:
		var consts: Dictionary = entries[folder]
		lines.append("## %s" % folder)
		for key in consts:
			lines.append('const %s := "%s"' % [key, consts[key]])
		lines.append("")
	return "\n".join(lines)


func _count_constants(entries: Dictionary) -> int:
	var total := 0
	for folder in entries:
		total += entries[folder].size()
	return total


func _write_file(code: String) -> void:
	var global_path := ProjectSettings.globalize_path(OUTPUT_PATH)
	var dir := DirAccess.open(ProjectSettings.globalize_path("res://scripts"))
	if dir and not dir.dir_exists_absolute("tools"):
		dir.make_dir_absolute("tools")
	var file := FileAccess.open(global_path, FileAccess.WRITE)
	if file == null:
		push_error("Cannot write to %s" % OUTPUT_PATH)
		return
	file.store_string(code)
	file.close()
