## AUTO-GENERATED by generate_asset_registry.gd — do not edit manually.
class_name AssetRegistry


## GENERATED
const GENERATED_ICON_CLICK := "res://assets/generated/icon_click.png"

## ICONS
const ICONS_ICON_CHOP := "res://assets/icons/icon_chop.png"
const ICONS_ICON_GEAR := "res://assets/icons/icon_gear.png"
const ICONS_ICON_GLOBE := "res://assets/icons/icon_globe.png"
const ICONS_ICON_GLOBE_SMALL := "res://assets/icons/icon_globe_small.png"
const ICONS_ICON_GLOBE_W := "res://assets/icons/icon_globe_w.png"
const ICONS_ICON_LOCK := "res://assets/icons/icon_lock.png"
const ICONS_ICON_LOCK_W := "res://assets/icons/icon_lock_w.png"
const ICONS_ICON_LOGIN := "res://assets/icons/icon_login.png"
const ICONS_ICON_LOGOUT := "res://assets/icons/icon_logout.png"
const ICONS_ICON_MINE := "res://assets/icons/icon_mine.png"
const ICONS_ICON_PAN := "res://assets/icons/icon_pan.png"
const ICONS_ICON_RESOURCE := "res://assets/icons/icon_resource.png"
const ICONS_ICON_USER := "res://assets/icons/icon_user.png"
const ICONS_ICON_USER_W := "res://assets/icons/icon_user_w.png"

## ROOT
const PLAYER := "res://assets/player.png"

## RESOURCES
const RESOURCES_GOLD_DEPLETED := "res://assets/resources/gold_depleted.png"
const RESOURCES_GOLD_NUGGET := "res://assets/resources/gold_nugget.png"
const RESOURCES_ICON_FARM := "res://assets/resources/icon_farm.png"
const RESOURCES_ICON_FOOD := "res://assets/resources/icon_food.png"
const RESOURCES_ICON_GOLD := "res://assets/resources/icon_gold.png"
const RESOURCES_ICON_LUMBER_CAMP := "res://assets/resources/icon_lumber_camp.png"
const RESOURCES_ICON_MINE := "res://assets/resources/icon_mine.png"
const RESOURCES_ICON_QUARRY := "res://assets/resources/icon_quarry.png"
const RESOURCES_ICON_STONE := "res://assets/resources/icon_stone.png"
const RESOURCES_ICON_UPGRADE := "res://assets/resources/icon_upgrade.png"
const RESOURCES_ICON_WOOD := "res://assets/resources/icon_wood.png"
const RESOURCES_STONE := "res://assets/resources/stone.png"
const RESOURCES_STONE_DEPLETED := "res://assets/resources/stone_depleted.png"

## TREES
const TREES_TREE := "res://assets/trees/tree.png"
const TREES_TREE_STUMP := "res://assets/trees/tree_stump.png"

## UI
const UI_BG_LOGIN := "res://assets/ui/bg_login.png"
const UI_LOGO_CART := "res://assets/ui/logo_cart.png"
const UI_LOGO_CONSOLE := "res://assets/ui/logo_console.png"

## SCENES
const SCENES_CLICK_EFFECT := "res://scenes/click_effect.tscn"
const SCENES_ENGINE_BUTTON := "res://scenes/engine_button.tscn"
const SCENES_GAME := "res://scenes/game.tscn"
const SCENES_GOLD_SOURCE := "res://scenes/gold_source.tscn"
const SCENES_LANG_BUTTON := "res://scenes/lang_button.tscn"
const SCENES_LANG_DROPDOWN := "res://scenes/lang_dropdown.tscn"
const SCENES_LOGIN := "res://scenes/login.tscn"
const SCENES_MAIN := "res://scenes/main.tscn"
const SCENES_QUIT_POPUP := "res://scenes/quit_popup.tscn"
const SCENES_RENDER_ENGINE_DROPDOWN := "res://scenes/render_engine_dropdown.tscn"
const SCENES_RESOURCE_GAME := "res://scenes/resource_game.tscn"
const SCENES_SETTINGS_BUTTON := "res://scenes/settings_button.tscn"
const SCENES_STONE := "res://scenes/stone.tscn"
const SCENES_TREE := "res://scenes/tree.tscn"

## SHADERS
const SHADERS_REBORN_GLOW := "res://shaders/reborn_glow.gdshader"

## TRANSLATIONS
const TRANSLATIONS_TRANSLATIONS := "res://translations/translations.csv"
const TRANSLATIONS_TRANSLATIONS_EN := "res://translations/translations.en.translation"
const TRANSLATIONS_TRANSLATIONS_VI := "res://translations/translations.vi.translation"

## DATA
const DATA_RESOURCES := "res://data/resources.yml"
